name: build al8 image
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install docker
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y needrestart || true
          sudo apt install -y bash wget
          sudo ln -svf bash /bin/sh
          sudo /bin/bash scripts/clean-os.sh
          sudo apt upgrade -y -qqq
          sudo /bin/rm -fr /tmp/*
          sudo /bin/bash scripts/install-docker.sh

      - name: Build almalinux 8
        run: >
          sudo docker build --no-cache -t "${{ secrets.DOCKERHUB_USERNAME }}"/almalinux:8 -f dockerfiles/al8/Dockerfile dockerfiles/al8/;
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin;
          sudo docker push "${{ secrets.DOCKERHUB_USERNAME }}"/almalinux:8;
          sudo systemctl stop docker.socket docker.service containerd.service;
          sudo /bin/rm -fr /var/lib/docker/* ;
          sudo /bin/rm -fr /var/lib/containerd/* ;
          sudo /bin/rm -fr /mnt/docker-data/*
