name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: |
          sudo apt update -y -qqq
          sudo apt install -y bash wget ca-certificates curl git
          sudo ln -svf bash /bin/sh
          sudo bash sethost/.pre
          sudo apt upgrade -fy -qqq
          sudo bash sethost/install_docker.sh
      - name: Build almalinux 8
        run: |
          sudo docker build --no-cache -t "${{ secrets.DOCKERHUB_USERNAME }}"/almalinux:8 almalinux8/
          sudo docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password="${{ secrets.DOCKERHUB_TOKEN }}"
          sudo docker push "${{ secrets.DOCKERHUB_USERNAME }}"/almalinux:8
